//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace smit05_BigProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketGoEntities : DbContext
    {
        public MarketGoEntities()
            : base("name=MarketGoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MGadminLogin> MGadminLogins { get; set; }
        public virtual DbSet<MGcomment> MGcomments { get; set; }
        public virtual DbSet<MGevent> MGevents { get; set; }
        public virtual DbSet<MGmember> MGmembers { get; set; }
        public virtual DbSet<MGsellerCheck> MGsellerChecks { get; set; }
        public virtual DbSet<MGsellerSign> MGsellerSigns { get; set; }
        public virtual DbSet<MGwishlist> MGwishlists { get; set; }
    }
}
