//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace smit05_BigProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGcomment
    {
        public int C_ID { get; set; }
        public string C_name { get; set; }
        public Nullable<int> C_sexcial { get; set; }
        public string C_email { get; set; }
        public string C_content { get; set; }
    }
}
