//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace smit05_BigProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGmember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MGmember()
        {
            this.MGevents = new HashSet<MGevent>();
            this.MGsellerSigns = new HashSet<MGsellerSign>();
            this.MGwishlists = new HashSet<MGwishlist>();
        }
    
        public int M_ID { get; set; }
        public string M_account { get; set; }
        public string M_password { get; set; }
        public string M_password_check { get; set; }
        public string M_email { get; set; }
        public string M_identity { get; set; }
        public string M_host_name { get; set; }
        public string M_host_page { get; set; }
        public string M_host_people { get; set; }
        public string M_host_about { get; set; }
        public string M_host_image { get; set; }
        public string M_contact_name { get; set; }
        public string M_sexcial { get; set; }
        public string M_contact_address { get; set; }
        public string M_contact_tel { get; set; }
        public string M_seller_name { get; set; }
        public string M_seller_page { get; set; }
        public string M_seller_about { get; set; }
        public string M_seller_image { get; set; }
        public string M_seller_exp { get; set; }
        public string M_seller_I1 { get; set; }
        public string M_seller_I2 { get; set; }
        public string M_seller_I3 { get; set; }
        public string M_seller_I4 { get; set; }
        public string M_seller_I5 { get; set; }
        public string M_seller_I6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGevent> MGevents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGsellerSign> MGsellerSigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MGwishlist> MGwishlists { get; set; }
    }
}
