//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace smit05_BigProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGsellerSign
    {
        public int SS_ID { get; set; }
        public int E_ID { get; set; }
        public int M_ID { get; set; }
        public int SS_num { get; set; }
        public string SS_note { get; set; }
        public int SC_ID { get; set; }
    
        public virtual MGevent MGevent { get; set; }
        public virtual MGevent MGevent1 { get; set; }
        public virtual MGmember MGmember { get; set; }
        public virtual MGsellerCheck MGsellerCheck { get; set; }
    }
}
